// apps/app-react/src/components/Modal.tsx
import { ReactNode, useEffect } from "react";

type Props = {
  title: string;
  children: ReactNode[];
  onDestroyModal?: () => void;
};

const Modal = ({ title, children: [body, footer], onDestroyModal }: Props) => {
  useEffect(() => {
    return () => {
      onDestroyModal?.();
    };
  }, []);

  return (
    <div className="modal">
      <div className="modal-backdrop"></div>
      <div className="modal-content">
        {/* Modal header */}
        <div className="modal-header">
          <h3 className="modal-title">{title}</h3>
        </div>
        {/* Modal body */}
        <div className="modal-body">{body}</div>
        {/* Modal footer  */}
        <div className="modal-footer">{footer}</div>
      </div>
    </div>
  );
};

export default Modal;

// apps/app-svelte/src/lib/components/Modal.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy } from "svelte";

  export let title: string;
  export let onDestroyModal: (() => void) | null = null;

  onDestroy(() => {
    onDestroyModal?.();
  });
</script>

<div class="modal">
  <div class="modal-backdrop"></div>
  <div class="modal-content">
    <!-- Modal header -->
    <div class="modal-header">
      <h3 class="modal-title">{title}</h3>
    </div>
    <!-- Modal body -->
    <div class="modal-body">
      <slot name="body" />
    </div>
    <!-- Modal footer -->
    <div class="modal-footer">
      <slot name="footer" />
    </div>
  </div>
</div>
