// apps/app-react/src/components/TodoFilter.tsx
import { SEARCH_SELECT_OPTIONS, SearchCriteria } from "common";
import FormInput from "./FormInput";
import FormSelect from "./FormSelect";
import { useEffect, useRef, useState } from "react";

type Props = {
  onCriteriaChange: (searchCriteria: SearchCriteria) => void;
};

const TodoFilter = ({ onCriteriaChange }: Props) => {
  const timeoutId = useRef<number | undefined>(undefined);
  const [inputTitle, setInputTitle] = useState<string>("");
  const [inputDeadline, setInputDeadline] = useState<string>("");
  const [selectedStatus, setSelectedStatus] = useState(
    SEARCH_SELECT_OPTIONS[0],
  );

  useEffect(() => {
    clearTimeout(timeoutId.current);
    timeoutId.current = setTimeout(() => {
      onCriteriaChange({
        title: inputTitle.trim(),
        deadline: inputDeadline.trim(),
        status: selectedStatus.id,
      });
    }, 500);
  }, [inputTitle, inputDeadline, selectedStatus]);

  return (
    <div className="py-2 flex gap-2">
      <FormInput
        id="filter-title"
        title="タイトル"
        value={inputTitle}
        onChange={e => setInputTitle(e.currentTarget.value)}
      />
      <FormInput
        id="filter-deadline"
        title="期日"
        inputType="date"
        value={inputDeadline}
        onChange={e => setInputDeadline(e.currentTarget.value)}
      />
      <FormSelect<(typeof SEARCH_SELECT_OPTIONS)[number]>
        title="ステータス"
        id="filter-status"
        options={SEARCH_SELECT_OPTIONS}
        value={selectedStatus}
        onChange={option => setSelectedStatus(option)}
      />
    </div>
  );
};

export default TodoFilter;

// apps/app-svelte/src/lib/components/TodoFilter.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import FormSelect from "$lib/components/FormSelect.svelte";
  import FormInput from "$lib/components/FormInput.svelte";
  import {
    SEARCH_SELECT_OPTIONS,
    withTimeout,
    type SearchCriteria,
  } from "common";

  const dispatch = createEventDispatcher<{ criteriaChange: SearchCriteria }>();

  let inputTitle: string = "";
  let inputDeadline: string = "";
  let selectedStatus = SEARCH_SELECT_OPTIONS[0];
  let timeoutId: NodeJS.Timeout | undefined = undefined;

  const updateTimeout = (callback: () => void) => {
    clearTimeout(timeoutId);
    timeoutId = setTimeout(() => {
      callback();
    }, 500);
  };

  $: {
    updateTimeout(() => {
      dispatch("criteriaChange", {
        title: inputTitle.trim(),
        deadline: inputDeadline.trim(),
        status: selectedStatus.id,
      });
    });
  }
</script>

<div class="py-2 flex gap-2">
  <FormInput id="filter-title" title="タイトル" bind:value={inputTitle} />
  <FormInput
    id="filter-deadline"
    title="期日"
    inputType="date"
    bind:value={inputDeadline}
  />
  <FormSelect
    title="ステータス"
    id="filter-status"
    options={SEARCH_SELECT_OPTIONS}
    bind:value={selectedStatus}
  />
</div>
