// apps/app-svelte/src/lib/components/FormSelect.svelte
<script lang="ts" generics="T extends { text: string }">
  export let id: string | null= null;
  export let title: string = '';
  export let value: T;
  export let options: T[];
</script>

<div class="form-group">
  {#if title && id}
    <label for={id} class="form-label">{title}</label>
  {/if}
  <select id={id} class="form-input" bind:value>
    {#each options as option}
      <option value={option}>
        {option.text}
      </option>
    {/each}
  </select>
</div>

// apps/app-vue/src/components/FormSelect.vue
<script setup lang="ts" generic="T extends { text: string; id: number }">
defineProps<{
  id?: string;
  title?: string;
  options: T[];
}>();

const value = defineModel<T>("value");
</script>

<template>
  <div class="form-group">
    <label v-if="title && id" for="id" class="form-label">{{ title }}</label>
    <select :id="id" class="form-input" v-model="value">
      <option v-for="option in options" :value="option" :key="option.id">
        {{ option.text }}
      </option>
    </select>
  </div>
</template>
