// apps/app-svelte/src/lib/components/TodoFilter.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import FormSelect from "$lib/components/FormSelect.svelte";
  import FormInput from "$lib/components/FormInput.svelte";
  import {
    SEARCH_SELECT_OPTIONS,
    withTimeout,
    type SearchCriteria,
  } from "common";

  const dispatch = createEventDispatcher<{ criteriaChange: SearchCriteria }>();

  let inputTitle: string = "";
  let inputDeadline: string = "";
  let selectedStatus = SEARCH_SELECT_OPTIONS[0];
  let timeoutId: NodeJS.Timeout | undefined = undefined;

  const updateTimeout = (callback: () => void) => {
    clearTimeout(timeoutId);
    timeoutId = setTimeout(() => {
      callback();
    }, 500);
  };

  $: {
    updateTimeout(() => {
      dispatch("criteriaChange", {
        title: inputTitle.trim(),
        deadline: inputDeadline.trim(),
        status: selectedStatus.id,
      });
    });
  }
</script>

<div class="py-2 flex gap-2">
  <FormInput id="filter-title" title="タイトル" bind:value={inputTitle} />
  <FormInput
    id="filter-deadline"
    title="期日"
    inputType="date"
    bind:value={inputDeadline}
  />
  <FormSelect
    title="ステータス"
    id="filter-status"
    options={SEARCH_SELECT_OPTIONS}
    bind:value={selectedStatus}
  />
</div>

// apps/app-vue/src/components/TodoFilter.vue
<script setup lang="ts">
import { SEARCH_SELECT_OPTIONS, type SearchCriteria } from "common";
import FormInput from "./FormInput.vue";
import { reactive, ref, watch } from "vue";
import FormSelect from "./FormSelect.vue";

type ReactiveInputs = {
  title: string;
  deadline: string;
  selectedStatus: (typeof SEARCH_SELECT_OPTIONS)[number];
};

const emits = defineEmits<{
  (name: "criteriaChange", searchCriteria: SearchCriteria): void;
}>();

const inputs = reactive<ReactiveInputs>({
  title: "",
  deadline: "",
  selectedStatus: SEARCH_SELECT_OPTIONS[0],
});
const timeoutId = ref<number | undefined>(undefined);

watch(inputs, (newValue: ReactiveInputs) => {
  clearTimeout(timeoutId.value);
  timeoutId.value = setTimeout(() => {
    emits("criteriaChange", {
      ...newValue,
      status: newValue.selectedStatus.id,
    });
  }, 300);
});
</script>

<template>
  <div class="py-2 flex gap-2">
    <FormInput
      id="filter-title"
      title="タイトル"
      v-model:value="inputs.title"
    />
    <FormInput
      id="filter-deadline"
      title="期日"
      inputType="date"
      v-model:value="inputs.deadline"
    />
    <FormSelect
      title="ステータス"
      id="filter-status"
      :options="SEARCH_SELECT_OPTIONS"
      v-model:value="inputs.selectedStatus"
    />
  </div>
</template>
