// apps/app-vue/src/App.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, ref } from "vue";
import {
  type Todo,
  postTodo,
  getTodoList,
  OPTIONS,
  deleteTodo,
  filterTodoList,
  SearchCriteria,
  updateTodo,
} from "common";
import Header from "./components/Header.vue";
import FormInput from "./components/FormInput.vue";
import TodoTable from "./components/TodoTable.vue";
import TodoFilter from "./components/TodoFilter.vue";
import Modal from "./components/Modal.vue";
import FormSelect from "./components/FormSelect.vue";

const editTitleRef = ref<InstanceType<typeof FormInput> | null>(null);
const titleInput = ref<string>("");
const deadlineInput = ref<string>("");
const editTitleInput = ref<string>("");
const editDeadlineInput = ref<string>("");
const editStatusSelect = ref<(typeof OPTIONS)[number]>(OPTIONS[0]);
const todoList = ref<Todo[]>([]);
const editTodo = ref<Todo | null>(null);
const openEditModal = ref<boolean>(false);
const searchCriteria = ref<SearchCriteria>({
  title: "",
  deadline: "",
  status: -1,
});

const init = async () => {
  const res = await getTodoList();
  todoList.value = res.data;
  titleInput.value = "";
  deadlineInput.value = "";
};

const onDestroyModal = () => {
  editTodo.value = null;
  editTitleInput.value = "";
  editDeadlineInput.value = "";
  editStatusSelect.value = OPTIONS[0];
};

const onClickTodoRow = async (index: number) => {
  const targetTodo = todoList.value[index];
  const statusOptions = OPTIONS.find(option => {
    return option.id === targetTodo.status;
  });
  editTodo.value = targetTodo;
  editTitleInput.value = targetTodo.title;
  editDeadlineInput.value = targetTodo.deadline;
  openEditModal.value = true;
  if (statusOptions) {
    editStatusSelect.value = statusOptions;
  }

  await nextTick();
  if (editTitleRef.value) {
    editTitleRef.value?.focus();
  }
};

const onClickTodoDelete = async (index: number) => {
  const targetTodo = todoList.value[index];
  if (targetTodo) {
    const deleteId = targetTodo.id;
    await deleteTodo(deleteId);
    init();
  }
};

const onClickAdd = async () => {
  await postTodo({
    title: titleInput.value,
    deadline: deadlineInput.value,
  });
  init();
};

const onClickUpdateModal = async () => {
  if (editTodo.value) {
    await updateTodo({
      ...editTodo.value,
      deadline: editDeadlineInput.value,
      title: editTitleInput.value,
      status: editStatusSelect.value.id,
    });
    await init();
  }
  openEditModal.value = false;
};

const onClickCancelModal = () => {
  openEditModal.value = false;
};

const onCriteriaChange = (_searchCriteria: SearchCriteria) => {
  searchCriteria.value = _searchCriteria;
};

const filteredTodoList = computed<Todo[]>(() => {
  return filterTodoList(todoList.value, searchCriteria.value);
});

const canAdd = computed<boolean>(() => {
  return (
    titleInput.value.trim().length > 0 && deadlineInput.value.trim().length > 0
  );
});

onMounted(() => {
  init();
});
</script>

<template>
  <Header />
  <main class="p-md flex flex-col gap-2">
    <!-- TodoInputArea -->
    <div class="card">
      <div class="card-header">新しいTODOの追加</div>

      <div class="p-lg flex flex-col gap-2">
        <FormInput
          title="タイトル"
          id="title-input"
          v-model:value="titleInput"
        />
        <FormInput
          title="期日"
          inputType="date"
          id="deadline-input"
          v-model:value="deadlineInput"
        />
        <div class="mt-2">
          <button
            class="btn btn-primary w-full"
            :disabled="!canAdd"
            @click="onClickAdd"
          >
            追加
          </button>
        </div>
      </div>
    </div>

    <!-- TodoDisplayArea -->
    <div class="card">
      <div class="card-header">TODOリスト</div>
      <div class="p-lg">
        <TodoFilter @criteriaChange="onCriteriaChange" />

        <TodoTable
          @clickRow="onClickTodoRow"
          @clickDelete="onClickTodoDelete"
          :todoList="filteredTodoList"
        />
      </div>
    </div>

    <!-- EditModalArea -->
    <Transition name="fade">
      <Modal
        v-if="openEditModal"
        title="TODOの編集"
        :onDestroyModal="onDestroyModal"
      >
        <template v-slot:body>
          <div class="flex flex-col gap-2">
            <FormInput
              id="edit-title-input"
              title="タイトル"
              ref="editTitleRef"
              v-model:value="editTitleInput"
            />
            <FormInput
              id="edit-deadline-input"
              title="期日"
              inputType="date"
              v-model:value="editDeadlineInput"
            />

            <FormSelect
              id="edit-status-select"
              title="ステータス"
              :options="OPTIONS"
              v-model:value="editStatusSelect"
            />
          </div>
        </template>

        <template v-slot:footer>
          <div class="flex w-full gap-2">
            <div class="flex-1" />
            <button class="btn btn-secondary" @click="onClickCancelModal">
              キャンセル
            </button>
            <button class="btn btn-primary" @click="onClickUpdateModal">
              更新
            </button>
          </div>
        </template>
      </Modal>
    </Transition>
  </main>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// apps/app-react/src/App.tsx
import "style/src/index.css";
import { useEffect, useMemo, useRef, useState } from "react";
import {
  deleteTodo,
  filterTodoList,
  getTodoList,
  OPTIONS,
  postTodo,
  updateTodo,
  type SearchCriteria,
  type Todo,
} from "common";
import Header from "./components/Header";
import FormInput, { FormInputHandle } from "./components/FormInput";
import TodoTable from "./components/TodoTable";
import Modal from "./components/Modal";
import FormSelect from "./components/FormSelect";
import TodoFilter from "./components/TodoFilter";

function App() {
  const editTitleRef = useRef<FormInputHandle>(null);
  const [titleInput, setTitleInput] = useState<string>("");
  const [deadlineInput, setDeadlineInput] = useState<string>("");
  const [editTitleInput, setEditTitleInput] = useState<string>("");
  const [editDeadlineInput, setEditDeadlineInput] = useState<string>("");
  const [editStatusSelect, setEditStatusSelect] = useState<
    (typeof OPTIONS)[number]
  >(OPTIONS[0]);
  const [todoList, setTodoList] = useState<Todo[]>([]);
  const [editTodo, setEditTodo] = useState<Todo | null>(null);
  const [openEditModal, setOpenEditModal] = useState<boolean>(false);
  const [searchCriteria, setSearchCriteria] = useState<SearchCriteria>({
    title: "",
    deadline: "",
    status: -1,
  });

  const init = async () => {
    const res = await getTodoList();
    setTodoList(res.data);
    setTitleInput("");
    setDeadlineInput("");
  };

  const onDestroyModal = () => {
    setEditTodo(null);
    setEditTitleInput("");
    setEditDeadlineInput("");
    setEditStatusSelect(OPTIONS[0]);
  };

  const onClickTodoRow = async (index: number) => {
    const targetTodo = todoList[index];
    const statusOptions = OPTIONS.find(option => {
      return option.id === targetTodo.status;
    });
    setEditTodo(targetTodo);
    setEditTitleInput(targetTodo.title);
    setEditDeadlineInput(targetTodo.deadline);
    setOpenEditModal(true);
    if (statusOptions) {
      setEditStatusSelect(statusOptions);
    }

    setTimeout(() => {
      if (editTitleRef.current) {
        editTitleRef.current.focus();
      }
    });
  };

  const onClickTodoDelete = async (index: number) => {
    const targetTodo = todoList[index];
    if (targetTodo) {
      const deleteId = targetTodo.id;
      await deleteTodo(deleteId);
      init();
    }
  };

  const onClickAdd = async () => {
    await postTodo({
      title: titleInput,
      deadline: deadlineInput,
    });
    init();
  };

  const onClickUpdateModal = async () => {
    if (editTodo) {
      await updateTodo({
        ...editTodo,
        deadline: editDeadlineInput,
        title: editTitleInput,
        status: editStatusSelect.id,
      });
      await init();
    }
    setOpenEditModal(false);
  };

  const onClickCancelModal = () => {
    setOpenEditModal(false);
  };

  const onCriteriaChange = (searchCriteria: SearchCriteria) => {
    setSearchCriteria(searchCriteria);
  };

  const filteredTodoList = useMemo<Todo[]>(() => {
    return filterTodoList(todoList, searchCriteria);
  }, [todoList, searchCriteria]);

  const canAdd = useMemo<boolean>(
    () => titleInput.trim().length > 0 && deadlineInput.trim().length > 0,
    [titleInput, deadlineInput],
  );

  useEffect(() => {
    init();
  }, []);

  return (
    <div>
      <Header />

      <main className="p-md flex flex-col gap-2">
        {/* TodoInputArea */}
        <div className="card">
          <div className="card-header">新しいTODOの追加</div>

          <div className="p-lg flex flex-col gap-2">
            <FormInput
              title="タイトル"
              id="title-input"
              value={titleInput}
              onChange={e => setTitleInput(e.currentTarget.value)}
            />
            <FormInput
              title="期日"
              inputType="date"
              id="deadline-input"
              value={deadlineInput}
              onChange={e => setDeadlineInput(e.currentTarget.value)}
            />
            <div className="mt-2">
              <button
                className="btn btn-primary w-full"
                disabled={!canAdd}
                onClick={onClickAdd}
              >
                追加
              </button>
            </div>
          </div>
        </div>

        {/* TodoDisplayArea */}
        <div className="card">
          <div className="card-header">TODOリスト</div>
          <div className="p-lg">
            <TodoFilter onCriteriaChange={onCriteriaChange} />

            <TodoTable
              onClickRow={onClickTodoRow}
              onClickDelete={onClickTodoDelete}
              todoList={filteredTodoList}
            />
          </div>
        </div>

        {/* EditModalArea  */}
        {openEditModal && (
          <Modal title={"TODOの編集"} onDestroyModal={onDestroyModal}>
            <div className="flex flex-col gap-2">
              <FormInput
                id="edit-title-input"
                title="タイトル"
                ref={editTitleRef}
                value={editTitleInput}
                onChange={e => setEditTitleInput(e.currentTarget.value)}
              />
              <FormInput
                id="edit-deadline-input"
                title="期日"
                inputType="date"
                value={editDeadlineInput}
                onChange={e => setEditDeadlineInput(e.currentTarget.value)}
              />

              <FormSelect<(typeof OPTIONS)[number]>
                id="edit-status-select"
                title="ステータス"
                options={OPTIONS}
                value={editStatusSelect}
                onChange={todo => setEditStatusSelect(todo)}
              />
            </div>
            <div className="flex w-full gap-2">
              <div className="flex-1" />
              <button
                className="btn btn-secondary"
                onClick={onClickCancelModal}
              >
                キャンセル
              </button>
              <button className="btn btn-primary" onClick={onClickUpdateModal}>
                更新
              </button>
            </div>
          </Modal>
        )}
      </main>
    </div>
  );
}

export default App;
